
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: track-leave_development

test:
  <<: *default
  database: track-leave_test

production:
  <<: *default
  database: track-leave_production
  username: track-leave
  password: <%= ENV['TRACK-LEAVE_DATABASE_PASSWORD'] %>
